class WisataData {
  String name;
  String category;
  String openTimes;
  String price;
  String openDays;
  String location;
  String imageAsset;
  String description;
  List<String> imgSlide;

  WisataData({
    required this.name,
    required this.category,
    required this.openTimes,
    required this.price,
    required this.openDays,
    required this.location,
    required this.imageAsset,
    required this.description,
    required this.imgSlide,
  });
}

var WisataDataList = [
  WisataData(
  name: 'Jembatan Ampera',
  category: 'Budaya',
  openTimes: '24 Jam',
  price: 'Gratis',
  openDays: 'Setiap Hari', 
  location: 'https://maps.app.goo.gl/P1EUT8XV1MDX9rKPA', 
  imageAsset: 'images/JA1.jpg', 
  description: 'Jembatan Ampera di Palembang adalah landmark bersejarah yang menghubungkan Seberang Ulu dan Seberang Ilir di atas Sungai Musi, dibangun pada tahun 1962 sebagai simbol persahabatan antara Indonesia dan Jepang. Jembatan ini awalnya dirancang untuk bisa diangkat guna memberi ruang bagi kapal besar yang melintasi Sungai Musi, meskipun fungsi tersebut kini tidak lagi digunakan. Tidak ada tiket masuk untuk menikmati Jembatan Ampera karena ini adalah fasilitas publik, dan jembatan ini terbuka selama 24 jam setiap hari. Jembatan ini menjadi salah satu spot populer bagi wisatawan, terutama pada malam hari ketika lampu-lampu menghiasi struktur megahnya, memberikan nuansa khas bagi kota Palembang.', 
  imgSlide: [
    'JA2.jpg',
    'JA3.jpg',
    'JA4.jpg',
  ],
  ),
  WisataData(
    name: 'Museum BalaPutra Dewa', 
    category: 'Budaya', 
    openTimes: '08.30 - 15.30', 
    price: 'Rp2.000-Rp15.000', 
    openDays: 'Selasa - Minggu', 
    location: 'https://maps.app.goo.gl/1VUUr8h6mGaumSfr9 ', 
    imageAsset: 'images/MBD1.jpg', 
    description: 'Museum Bala Putra Dewa di Palembang adalah museum kebanggaan Sumatra Selatan yang menampilkan sejarah dan budaya khas daerah ini, termasuk artefak Kerajaan Sriwijaya dan peninggalan Kesultanan Palembang. Museum ini menawarkan berbagai koleksi seperti senjata tradisional, keramik, tekstil, serta replika rumah adat Limas. Tiket masuk museum ini terjangkau, sekitar Rp 5.000 hingga Rp 10.000 per orang, tergantung usia dan status pelajar. Jam operasional museum biasanya dari pukul 08.00 hingga 15.00 pada hari Selasa hingga Minggu, sedangkan Senin museum tutup untuk pemeliharaan. Museum Bala Putra Dewa tidak hanya menjadi pusat edukasi sejarah, tetapi juga menjaga identitas budaya Sumatra Selatan untuk generasi mendatang.', 
    imgSlide: [
      'MBD2.jpg',
      'MBD3.jpg',
      'MBD4.jpg',
    ],
    ),
    WisataData(
    name: 'Museum Sultan Mahmud Badarudin II', 
    category: 'Budaya', 
    openTimes: '08.00 - 16.00', 
    price: 'Rp1.000 - Rp20.000', 
    openDays: 'Selasa - Minggu', 
    location: 'https://maps.app.goo.gl/YSYiZ5nBXz5xD7u79 ', 
    imageAsset: 'images/MS1.jpg', 
    description: 'Museum Sultan Mahmud Badaruddin di Palembang terletak di kawasan Benteng Kuto Besak, menampilkan sejarah dan budaya Kesultanan Palembang serta peninggalan Kerajaan Sriwijaya. Museum ini menyimpan beragam koleksi, mulai dari arca Buddha, senjata tradisional, hingga pakaian adat dan peninggalan Kesultanan. Harga tiket masuk museum ini sangat terjangkau, sekitar Rp 5.000 hingga Rp 10.000 per orang, menjadikannya pilihan wisata edukatif yang ramah di kantong. Museum ini beroperasi dari pukul 08.00 hingga 16.00 setiap hari kecuali Senin, di mana museum tutup untuk pemeliharaan. Museum Sultan Mahmud Badaruddin tidak hanya menjadi tempat wisata sejarah, tetapi juga simbol penting kebudayaan dan identitas kota Palembang.', 
    imgSlide: [
        'MS2.jpg',
        'MS3.jpg',
        'MS4.jpg',
    ],
    ),
    WisataData(
    name: 'Monpera (Monumen Perjuangan Rakyat)', 
    category: 'Budaya', 
    openTimes: '09.00 - 18.00', 
    price: 'Rp5.000', 
    openDays: 'Setiap Hari', 
    location: 'https://maps.app.goo.gl/ChWzJKDLhyEugiQMA ', 
    imageAsset: 'images/MON1.jpg', 
    description: 'Monumen Perjuangan Rakyat (Monpera) di Palembang adalah monumen bersejarah yang dibangun untuk menghormati perjuangan rakyat Sumatra Selatan melawan penjajahan. Bangunan ini memiliki bentuk unik yang melambangkan semangat kebersamaan dan perlawanan rakyat Palembang. Di dalamnya, terdapat museum kecil yang menyimpan koleksi foto, senjata, dan benda-benda bersejarah lainnya yang menggambarkan kisah heroik perjuangan kemerdekaan. Tiket masuk Monpera umumnya sangat terjangkau, sekitar Rp 3.000 hingga Rp 5.000 per orang. Monumen ini buka setiap hari dari pukul 08.00 hingga 16.00, menjadikannya tempat yang ideal bagi wisatawan yang ingin memahami lebih dalam tentang sejarah perjuangan di Palembang.', 
    imgSlide: [
          'MON2.jpg',
          'MON3.jpg',
          'MON4.jpg',
    ],
    ),
    WisataData(
    name: 'Benteng Kuto Besak', 
    category: 'Budaya', 
    openTimes: '08.00 - 21.00', 
    price: 'Rp5.000', 
    openDays: 'Setiap Hari', 
    location: 'https://maps.app.goo.gl/SN3YspKoRiKAaL3q7 ', 
    imageAsset: 'images/BKB1.jpg', 
    description: 'Benteng Kuto Besak (BKB) di Palembang adalah salah satu ikon sejarah kota yang dibangun pada abad ke-18. Benteng ini awalnya didirikan oleh Kesultanan Palembang untuk melindungi wilayahnya dari serangan kolonial. BKB sekarang menjadi daya tarik wisata populer karena arsitektur kuno dan nilai sejarahnya yang mencerminkan masa kejayaan kerajaan di Sumatra Selatan. Tiket masuk ke area sekitar BKB umumnya gratis, tetapi beberapa acara atau wahana di sekitar benteng mungkin memiliki biaya tambahan. Jam operasional BKB biasanya dari pagi hingga malam hari, sehingga pengunjung bisa menikmati suasana benteng saat senja. BKB juga terkenal sebagai tempat bersantai di tepi Sungai Musi, tempat wisatawan menikmati pemandangan sambil mengenang sejarah panjang Palembang.', 
    imgSlide: [
        'BKB2.jpg',
        'BKB3.jpg',
        'BKB4.jpg',
    ],
    ),
    WisataData(
    name: 'Punti Kayu', 
    category: 'Alam', 
    openTimes: '09.00 - 17.00', 
    price: 'Rp20.000 - Rp25.000', 
    openDays: 'Setiap Hari', 
    location: 'https://maps.app.goo.gl/d9Gu6mwNhMLiVuRo8 ', 
    imageAsset: 'images/PK1.jpg', 
    description: 'Punti Kayu di Palembang adalah taman wisata alam terbesar di kota ini, menawarkan suasana hutan pinus yang sejuk dan beragam aktivitas rekreasi. Tempat ini terkenal dengan area piknik, kebun binatang mini, serta danau dan wahana permainan yang cocok untuk wisata keluarga. Harga tiket masuk ke Punti Kayu biasanya berkisar antara Rp 10.000 hingga Rp 20.000 per orang, tergantung pada fasilitas yang ingin diakses. Taman ini buka setiap hari dari pukul 08.00 hingga 17.00, memungkinkan pengunjung menikmati waktu santai di tengah alam. Selain sebagai tempat rekreasi, Punti Kayu juga memiliki nilai sejarah sebagai bagian dari konservasi lingkungan dan paru-paru kota Palembang.', 
    imgSlide: [
      'PK3.jpg',
      'PK2.jpg',
      'PK4.jpg',
    ],
    ),
    WisataData(
    name: 'Masjid Agung Palembang', 
    category: 'Budaya', 
    openTimes: '24 jam', 
    price: 'Gratis', 
    openDays: 'Setiap Hari', 
    location: 'https://maps.app.goo.gl/5rSKmy9wR8QXLG7h7 ', 
    imageAsset: 'images/MAP3.jpg', 
    description: 'Masjid Agung Sultan Mahmud Badaruddin I di Palembang adalah masjid bersejarah yang dibangun pada abad ke-18 oleh Sultan Mahmud Badaruddin I, menjadikannya salah satu masjid tertua di Indonesia. Arsitektur masjid ini menggabungkan unsur Melayu, Tionghoa, dan Eropa, mencerminkan akulturasi budaya yang unik di Palembang. Tidak ada biaya masuk untuk berkunjung atau beribadah di masjid ini, dan masjid ini terbuka untuk umum setiap hari, dengan jam operasional dari pagi hingga malam. Selain sebagai tempat ibadah, Masjid Agung juga menjadi pusat kegiatan keagamaan dan simbol penting bagi umat Islam di Palembang. Masjid ini menyimpan nilai sejarah dan spiritual yang mendalam, sekaligus menjadi saksi perkembangan Islam di Sumatra Selatan.', 
    imgSlide: [
        'MAP1.jpg',
        'MAP2.jpg',
        'MAP4.jpg',
    ],
    ),
    WisataData(
    name: 'Masjid Cheng Ho Palembang', 
    category: 'Budaya', 
    openTimes: '04.00 - 21.00', 
    price: 'Gratis', 
    openDays: 'Setiap Hari', 
    location: 'https://maps.app.goo.gl/Paj4RJj5JTuNb9mw5 ', 
    imageAsset: 'images/MC1.jpg', 
    description: 'Masjid Cheng Ho di Palembang adalah masjid unik yang dibangun dengan arsitektur Tionghoa, Melayu, dan Arab untuk menghormati Laksamana Cheng Ho, seorang pelaut Muslim dari Tiongkok yang berperan penting dalam penyebaran Islam di Nusantara. Masjid ini memiliki desain khas berwarna merah, hijau, dan kuning, dengan ornamen-ornamen Tionghoa, menjadikannya tempat wisata religi yang menarik dan simbol harmonisasi budaya. Tidak ada biaya tiket masuk untuk mengunjungi masjid ini, dan masjid ini terbuka untuk umum setiap hari, mulai dari pagi hingga malam. Selain sebagai tempat ibadah, Masjid Cheng Ho juga menjadi pusat kegiatan sosial dan budaya bagi masyarakat Tionghoa Muslim di Palembang. Masjid ini melambangkan kerukunan antar budaya dan keberagaman dalam Islam di Indonesia.', 
    imgSlide: [
        'MC2.jpg',
        'MC3.jpg',
        'MC4.jpg',
    ],
    ),
    WisataData(
    name: 'Pulau Kemaro', 
    category: 'Budaya', 
    openTimes: '09.00 - 19.00', 
    price: 'Gratis', 
    openDays: 'Setiap Hari', 
    location: 'https://maps.app.goo.gl/wbWoyR4ZzsPQxQxH7', 
    imageAsset: 'images/PKP2.jpg', 
    description: 'Pulau Kemaro adalah pulau kecil di Sungai Musi, Palembang, yang terkenal dengan nilai sejarah dan mitos kisah cinta antara seorang putri Palembang dan pangeran Tiongkok. Di pulau ini, terdapat pagoda sembilan lantai dan Klenteng Hok Tjing Rio, yang menjadi tempat perayaan Cap Go Meh dan destinasi wisata budaya Tionghoa. Pengunjung biasanya tidak dikenakan tiket masuk, tetapi perlu menyewa perahu dari dermaga Sungai Musi untuk mencapai pulau. Pulau ini terbuka sepanjang hari, sehingga wisatawan dapat menikmati keindahan danau, arsitektur Tionghoa, serta mengunjungi makam bersejarah yang ada di sana. Pulau Kemaro bukan hanya destinasi wisata, tetapi juga simbol persahabatan budaya Indonesia dan Tiongkok di Palembang.' , 
    imgSlide: [
        'PKP1.jpg',
        'PKP3.jpg',
        'PKP4.jpg',
    ],
    ),
    WisataData(
    name: "Museum Bayt Al-Qur'an Akbar", 
    category: 'Budaya', 
    openTimes: '09.00 - 17.00', 
    price: 'Rp20.000', 
    openDays: 'Setiap Hari', 
    location: 'https://maps.app.goo.gl/KvvyzqNCLRW3BX8m8', 
    imageAsset: 'images/AAK1.jpg', 
    description: "Museum Bayt Al-Qur'an Al-Akbar di Palembang adalah museum unik yang menyimpan Al-Qur'an raksasa yang diukir di atas kayu tembesu, menjadikannya Al-Qur'an terbesar dan pertama di dunia dalam bentuk ukiran kayu. Setiap halaman Al-Qur'an ditampilkan di lembaran kayu besar yang dipahat dengan indah, sehingga menarik pengunjung dari berbagai daerah. Tiket masuk ke museum ini umumnya sekitar Rp 20.000 per orang, yang membantu menjaga dan merawat keindahan karya seni religius ini. Museum ini biasanya buka setiap hari dari pukul 09.00 hingga 17.00, sehingga pengunjung memiliki waktu untuk menikmati keagungan ukiran Al-Qur'an. Museum Bayt Al-Qur'an Al-Akbar tidak hanya menjadi simbol kebudayaan Islam, tetapi juga bukti kreativitas dan dedikasi masyarakat Palembang terhadap seni dan agama.", 
    imgSlide: [
        'AAK2.jpg',
        'AAK3.jpg',
        'AAK4.jpg',
    ],
    ),
    WisataData(
    name: 'Pempek Lala 26 Ilir', 
    category: 'Kuliner', 
    openTimes: '08.00 - 22.00', 
    price: 'Rp25.000 - Rp50.000/per orang', 
    openDays: 'Setiap Hari', 
    location: 'https://maps.app.goo.gl/ehFXxHWZU94SWdRd7', 
    imageAsset: 'images/PP1.jpg', 
    description: 'Pempek Lala di 26 Ilir Palembang adalah salah satu tempat terkenal untuk menikmati pempek asli dengan cita rasa khas yang autentik. Harga pempek di sini bervariasi, mulai dari Rp 2.000 hingga Rp 15.000 per potong, tergantung jenisnya seperti pempek kapal selam, lenjer, atau adaan. Pempek Lala biasanya buka setiap hari dari pukul 08.00 hingga 18.00, memungkinkan wisatawan maupun warga lokal menikmati makanan khas ini sepanjang hari. Selain cita rasa yang lezat, Pempek Lala juga menyediakan sambal cuko yang khas, menjadikannya favorit di kalangan pencinta kuliner Palembang.', 
    imgSlide: [
        'PP2.jpg',
        'PP3.jpg',
        'PP4.jpg',
    ],
    ),
    WisataData(
    name: 'Mie Celor 26 Ilir H. Syafei', 
    category: 'Kuliner', 
    openTimes: '06.00 - 22.00', 
    price: 'Rp25.000 - Rp50.000/per orang', 
    openDays: 'Setiap Hari', 
    location: 'https://maps.app.goo.gl/nTWJUn1o1vCNHELV9 ', 
    imageAsset: 'images/MCL1.jpg', 
    description: 'Mie Celor 26 Ilir H. Syafei adalah kedai legendaris di Palembang yang menyajikan mie celor khas dengan kuah santan kental dan udang, menghadirkan cita rasa gurih yang otentik. Harga seporsi mie celor di sini berkisar antara Rp 20.000 hingga Rp 30.000, sebanding dengan porsinya yang mengenyangkan dan kualitas bahan yang segar. Kedai ini buka setiap hari dari pukul 08.00 hingga 17.00, cocok bagi wisatawan dan warga lokal yang ingin menikmati sarapan atau makan siang. Dengan lokasi strategis dan cita rasa yang khas, Mie Celor H. Syafei menjadi destinasi kuliner favorit di Palembang, khususnya bagi pecinta mie celor tradisional.', 
    imgSlide: [
        'MCL2.jpg',
        'MCL3.jpg',
        'MCL4.jpg',
    ],
    ),
    WisataData(
    name: 'Pindang Khas Palembang', 
    category: 'Kuliner', 
    openTimes: '10.000 - 20.00', 
    price: 'Rp50.000 - Rp75.000/per orang', 
    openDays: 'Setiap Hari', 
    location: 'https://maps.app.goo.gl/rS2ehyeW8LwtMBmM9 ', 
    imageAsset: 'images/PU1.jpg', 
    description: 'Rumah Makan Pindang Umak di Palembang terkenal dengan sajian pindang khas Palembang yang kaya rempah dan memiliki cita rasa asam pedas yang segar. Harga hidangan di sini mulai dari Rp 25.000 hingga Rp 50.000 per porsi, tergantung pilihan ikan seperti patin, gabus, atau baung, yang disajikan dengan bumbu autentik. Restoran ini biasanya buka setiap hari dari pukul 10.00 hingga 21.00, menjadikannya tempat ideal untuk makan siang atau makan malam. Dengan suasana yang nyaman dan pelayanan ramah, Pindang Umak menjadi tempat favorit bagi pengunjung yang ingin menikmati hidangan tradisional Palembang dalam suasana yang santai.', 
    imgSlide: [
      'PU2.jpg',
      'PU3.jpg',
      'PU4.jpg',
    ],
    ),
    WisataData(
    name: 'Martabak Har', 
    category: 'Kuliner', 
    openTimes: '07.00 - 21.00' , 
    price: 'Rp25.000 - Rp50.000/per orang', 
    openDays: 'Setiap Hari', 
    location: 'https://maps.app.goo.gl/noLZLKaiUcVDVwmCA ', 
    imageAsset: 'images/MH3.jpg', 
    description: 'Martabak HAR di dekat Masjid Agung Palembang adalah salah satu kuliner legendaris di kota ini, terkenal dengan martabak telur yang disajikan bersama kuah kari kental yang gurih. Harga martabak di sini bervariasi, mulai dari Rp 15.000 hingga Rp 30.000, tergantung isian seperti telur ayam atau telur bebek. Kedai Martabak HAR ini buka setiap hari dari pukul 08.00 hingga 21.00, sehingga cocok untuk dinikmati sebagai sarapan, makan siang, maupun makan malam. Dengan lokasi strategis di dekat Masjid Agung dan cita rasa autentik yang diwariskan turun-temurun, Martabak HAR menjadi salah satu tempat favorit bagi pencinta kuliner khas Palembang.', 
    imgSlide: [
        'MH1.jpg',
        'MH2.jpg',
        'MH4.jpg',
    ],
    ),
];